### ISSUE TITLE
Installation of packages from outside sources

### ISSUE THREAD

**Issue by gamesh411** [whisperity/dotfiles-framework#1]
The package descriptions are currently part of the repository and there is no option to specify a package from outside (i.e. not in this repo) sources.
The outside source could be a git repository with a standard layout, or maybe a git repository with additional path-segments which specify the package descriptor JSON files.

**Comment by gamesh411** [comment]
@whisperity I really like this proposal, good job at laying out a reasonable implementation plan!

One thing I keep getting back to is the optionality of the remote name. On one hand, it would be nice to ensure that all remotes are identified by a unique name. On the other hand, as you mentioned we definitely wouldn't want to go down that "resolve remote dependency chains in a context-sensitive manner" rabbit hole (the context being all the other remote specifications). Not necessarily having a name for the remote discourages that general path, which is nice in its own way.

In my general use-case, I would like to provide a base that is my own (my shell .rc files and aliases). If I specify a remote before the default one, which has a package named `base`, I would want it to be used everywhere where `base` is defined as a dependency. Is this the correct assumption according to this implementation plan?

**Comment by whisperity** [comment]
@gamesh411 Yes, that's the plan. A dependency saying `base` to be installed will just "recursively" start looking up `base`. The first "source packages" where `base` is found (if it is not installed yet) will install `base` from there.

**Comment by whisperity** [comment]
I've did a few changes to the things said above.

1. The "logical name" of the *remote* repository will necessarily have to be specified. It'll be the first thing asked by the wizard.
2. There will be no way of specifying packages with a namespace prefix, such as `root::Package`. The problem is, keeping these names in check while also handling the resolution to an "unqualified" name is just too much of a hassle.

When Dotfiles loads the known packages, it will load in the order of remotes configured. Package "namespaces" (empty directories that only contain subdirectories) will be merged together, but trees rooted at an actual package and their subpackages **won't**. This means that if repository A contains `tools.fancy`, `vim`, `vim.foo` and repository B contains `tools.other`, `vim`, `vim.bar`, if loaded in an "AB" order, the available package names will be: `tools.fancy`, `tools.other`, `vim` (from A) and `vim.foo`.

Alternatively, you can specify `--source` to the install command which will restrict to **only** installing from that source, i.e. the "current" behaviour.

These things are done in the first step when package _names_ are fetched from the filesystem, and once this is done, only *one* copy of each package will be in memory.

**Comment by whisperity** [comment]
~~~
test$ ./dotfiles.py --source Local

| Source        | Package        | Description        |
| Local        | dummy        | A Dummy package        |
| Local        | test        |         |
~~~

This `test` depends on `basic`, however because the source list is restricted, it will not find the dependency and won't install.

~~~
test$ ./dotfiles.py --source Local test
KeyError: "Dependency 'basic' for 'test' was not found as a package."
~~~

**Comment by whisperity** [comment]
I think I've implemented this, @gamesh411, take a look at branch `multiple-sources`.

**Comment by gamesh411** [comment]
It's marvellous! I'm so glad that I can extend this framework in a modular fashion. Thanks!

**Comment by whisperity** [comment]
@gamesh411 So it works? Thanks! But do be careful, I'll be doing a bit of changes to the schema with regards to the `substitute environment variables` action, so I'll only merge this afterwards.
